-- Supabase Schema for OperFlow Integration with RLS enabled

-- 1. Create Tables
-- Companies
CREATE TABLE IF NOT EXISTS empresas (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome TEXT NOT NULL,
  cnpj TEXT UNIQUE NOT NULL,
  plano TEXT DEFAULT 'basic',
  status TEXT DEFAULT 'ativo',
  data_criacao TIMESTAMPTZ DEFAULT NOW()
);

-- Users (Admin/Consultants)
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  empresa_id BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  senha TEXT NOT NULL,
  perfil TEXT NOT NULL, -- 'admin', 'consultor'
  status TEXT DEFAULT 'online',
  avatar_url TEXT
);

-- Clients
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  empresa_id BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
  consultor_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  nome TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  senha TEXT NOT NULL,
  telefone TEXT,
  whatsapp_numero TEXT,
  whatsapp_notificacoes_ativas BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'ativo',
  avatar_url TEXT,
  faturamento NUMERIC DEFAULT 0,
  pedidos INTEGER DEFAULT 0,
  data_criacao TIMESTAMPTZ DEFAULT NOW()
);

-- Categories
CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  empresa_id BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
  nome TEXT NOT NULL
);

-- Priorities
CREATE TABLE IF NOT EXISTS prioridades (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  empresa_id BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  tempo_sla INTEGER NOT NULL -- in hours
);

-- Protocols
CREATE TABLE IF NOT EXISTS protocolos (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  empresa_id BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  titulo TEXT NOT NULL,
  descricao TEXT NOT NULL,
  categoria_id BIGINT REFERENCES categorias(id) ON DELETE SET NULL,
  prioridade_id BIGINT REFERENCES prioridades(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'aberto', -- 'aberto', 'em atendimento', 'aguardando cliente', 'concluido'
  responsavel_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  data_criacao TIMESTAMPTZ DEFAULT NOW(),
  data_fechamento TIMESTAMPTZ
);

-- Interactions
CREATE TABLE IF NOT EXISTS interacoes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  protocolo_id BIGINT REFERENCES protocolos(id) ON DELETE CASCADE,
  autor_id BIGINT NOT NULL,
  autor_tipo TEXT NOT NULL, -- 'admin', 'cliente'
  mensagem TEXT NOT NULL,
  anexo_url TEXT,
  visivel_cliente BOOLEAN DEFAULT TRUE,
  data_envio TIMESTAMPTZ DEFAULT NOW()
);

-- Channels
CREATE TABLE IF NOT EXISTS canais (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  nome TEXT NOT NULL, -- 'Mercado Livre', 'Amazon', 'Shopee'
  status TEXT DEFAULT 'ativo',
  status_cor TEXT DEFAULT 'verde',
  estoque_tipo TEXT DEFAULT 'Full',
  estoque_cor TEXT DEFAULT 'verde',
  data_atualizacao TIMESTAMPTZ DEFAULT NOW()
);

-- Evolution History
CREATE TABLE IF NOT EXISTS cliente_evolucao (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  consultor_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  titulo TEXT NOT NULL,
  descricao TEXT NOT NULL,
  visivel_cliente BOOLEAN DEFAULT TRUE,
  data_criacao TIMESTAMPTZ DEFAULT NOW()
);

-- Insights
CREATE TABLE IF NOT EXISTS insights (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  consultor_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  titulo TEXT NOT NULL,
  descricao TEXT NOT NULL,
  visivel_cliente BOOLEAN DEFAULT TRUE,
  data_criacao TIMESTAMPTZ DEFAULT NOW()
);

-- White-label Configuration
CREATE TABLE IF NOT EXISTS configuracoes_whitelabel (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  empresa_id BIGINT UNIQUE REFERENCES empresas(id) ON DELETE CASCADE,
  nome_sistema TEXT NOT NULL,
  logo_url TEXT,
  cor_primaria TEXT DEFAULT '#0a47c2',
  cor_secundaria TEXT DEFAULT '#fbbf24',
  cor_fundo_claro TEXT DEFAULT '#f5f6f8',
  cor_fundo_escuro TEXT DEFAULT '#101622',
  whatsapp_api_provider TEXT,
  whatsapp_api_token TEXT,
  whatsapp_numero_remetente TEXT,
  whatsapp_webhook_url TEXT
);

-- Products
CREATE TABLE IF NOT EXISTS produtos (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  empresa_id BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  sku TEXT NOT NULL,
  titulo TEXT NOT NULL,
  descricao TEXT,
  marca TEXT,
  preco_sugerido NUMERIC,
  imagem_principal_url TEXT,
  status TEXT DEFAULT 'ativo',
  data_criacao TIMESTAMPTZ DEFAULT NOW()
);

-- Protocol Products
CREATE TABLE IF NOT EXISTS protocolo_produtos (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  protocolo_id BIGINT REFERENCES protocolos(id) ON DELETE CASCADE,
  produto_id BIGINT REFERENCES produtos(id) ON DELETE CASCADE
);

-- Strategic Opinions (Pareceres)
CREATE TABLE IF NOT EXISTS pareceres (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
  consultor_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  conteudo TEXT NOT NULL,
  status_resultado TEXT NOT NULL, -- 'superou', 'dentro', 'atencao'
  data_criacao TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE empresas ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE prioridades ENABLE ROW LEVEL SECURITY;
ALTER TABLE protocolos ENABLE ROW LEVEL SECURITY;
ALTER TABLE interacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE canais ENABLE ROW LEVEL SECURITY;
ALTER TABLE cliente_evolucao ENABLE ROW LEVEL SECURITY;
ALTER TABLE insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracoes_whitelabel ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE protocolo_produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pareceres ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies (Example: Allow all access for now to facilitate sync)
-- Note: In a production environment, you should restrict access based on auth.uid()
-- These policies allow the 'anon' role (frontend) and 'authenticated' role to perform operations.

CREATE POLICY "Allow all access for anon" ON empresas FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON usuarios FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON clientes FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON categorias FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON prioridades FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON protocolos FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON interacoes FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON canais FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON cliente_evolucao FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON insights FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON configuracoes_whitelabel FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON produtos FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON protocolo_produtos FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for anon" ON pareceres FOR ALL TO anon USING (true) WITH CHECK (true);

-- Also allow authenticated users
CREATE POLICY "Allow all access for authenticated" ON empresas FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON usuarios FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON clientes FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON categorias FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON prioridades FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON protocolos FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON interacoes FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON canais FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON cliente_evolucao FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON insights FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON configuracoes_whitelabel FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON produtos FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON protocolo_produtos FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access for authenticated" ON pareceres FOR ALL TO authenticated USING (true) WITH CHECK (true);
